# Generated by Django 2.2.7 on 2019-11-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='remote_port',
        ),
    ]
